const { Pool } = require('pg');
const { nanoid } = require('nanoid');
const InvariantError = require('../../exceptions/InvariantError')

class CollaborationsService {
    constructor() {
        this._pool = new Pool();
    }
    async addCollaboration(playlistId, userId) {
        const id = `collab-${nanoid(16)}`;

        const query = {
            text: 'insert into collaborations values($1,$2, $3) returning id',
            values: [id, playlistId, userId],
        };
        const result = await this._pool.query(query);
        if (!result.rows.length) {
            throw new InvariantError('Kolaborasi gagal ditambahkan');
        }
        return result.rows[0].id;
    }


    async deleteCollaboration(playlistId, userId) {
        const query = {
            text: 'delete from collaborations WHERE playlist_id = $1 AND user_id = $2 returning id',
            values: [playlistId, userId],
        };
        const result = await this._pool.query(query);

        if (!result.rows.length) {
            throw new InvariantError('Kolaborasi gagal dihapus');
        }
    }

    async verifyColaborator(playlistId, userId) {
        const query = {
            text: 'select * from collaborations where playlist_id = $1 and user_id = $2 returning id',
            values: [playlistId, userId],
        };
        const result = await this._pool.query(query);
        if (!result.rows.length) {
            throw new InvariantError('kolaborasi gagal diverifikasi')
        }
    }

}

module.exports = CollaborationsService;